apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-app
  labels:
    app: foo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo-app
  template:
    metadata:
      labels:
        app: foo-app
        keda.sh/trigger: "http"
    spec:
      containers:
        - name: foo-app
          image: foo-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
