apiVersion: apps/v1
kind: Deployment
metadata:
  name: fizz-app
  labels:
    app: fizz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fizz-app
  template:
    metadata:
      labels:
        app: fizz-app
    spec:
      containers:
        - name: fizz-app
          image: foo-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "40m"
            limits:
              cpu: "50m"
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fizz-app
spec:
  selector:
    app: fizz-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fizz-app-hpa
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0 # Set to 0 for near instant HPA scale-down decision
      policies:
        - type: Percent
          value: 100
          periodSeconds: 1
    scaleUp:
      stabilizationWindowSeconds: 0 # Set to 0 for near instant HPA scale-up decision
      policies:
        - type: Percent
          value: 100
          periodSeconds: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fizz-app
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
