apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-app
  labels:
    app: ping-pong-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      containers:
        - name: ping-pong-app
          image: foo-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "10m"
            limits:
              cpu: "50m"
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-app
spec:
  selector:
    app: ping-pong-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: ping-pong-app-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ping-pong-app
  updatePolicy:
    updateMode: Recreate
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 50m
          memory: 10Mi
        maxAllowed:
          cpu: 2
          memory: 500Mi
        controlledResources: ["cpu", "memory"]